[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "src"
version = "0.1.0"
description = "A simple package"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["src"]